name: data
on:
  schedule:
    - cron: 5 4 * * 2
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.bungie.net/Platform/Destiny2/Manifest/
          authorization: X-API-KEY ${{secrets.X_API_KEY}}
          downloaded_filename: manifest.json
      - name: Read Manifest Version
        id: manifest
        uses: juliangruber/read-file-action@v1
        with:
          path: ./manifest.json
      - name: Set Version var
        run: echo ${{ steps.manifest.outputs.content.Response.version }}
